layout_spectrum: 0.9646558873355389
typography_spectrum: 0.7276719370856881
color:
  brandStrength: 0.9956205056514591
  lightness: 0.9667939764913172
  saturation: 0.34643627842888236
  rhythmicContrast: 0.4988993222359568
  brandColors:
    - '#FFFFFF'
    - '#545351'
    - '#B21876'
    - '#97969B'
    - '#C55197'
name: Disain Digesto
