typography_spectrum: 0.5423885935451835
color:
  brandStrength: 0.03437457303516567
  lightness: 0.71037752693519
  saturation: 0.03328672866337001
  rhythmicContrast: 0.2233605629298836
  brandColors:
    - '#545351'
    - '#97969B'
    - '#C55197'
    - '#FFFFFF'
    - '#171715'
opengraph:
  type: ''
layout_spectrum: 0.08764009363949299
author:
  name: Disain Digesto
  email: info@digesto.ee
  url: 'http://www.digesto.ee'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5440546a-93ce-4749-98e1-d51293a031d7.svg
name: Blog
navigation:
  - name: Website
    url: 'http://www.digesto.ee'
    type: external
  - name: New Web
    url: 'http://www.lavii.ee/disaindigesto'
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/digesto'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a905c698-a1fe-4296-9cfc-20cbcf49297c.png
title: Textile Magic
description: All new and noteworthy related to interior textiles
